language: node_js
node_js:
  - "12"

addons:
  chrome: stable

cache:
directories:
  - ./node_modules

script:
  - npm run test
  - npm run build -- --base-href /Angular/
  - cp dist/tp-angular/index.html dist/tp-angular/404.html
  
 deploy:
  provider: pages
  local_dir: dist/tp-angular
